### PR TITLE
Bump-build

### PR DESCRIPTION
**Pull request by corneliusroemer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by corneliusroemer** [comment]
@conda-forge-admin, please rerender

**Comment by BradHolmes** [comment]
Hi @corneliusroemer -- thank you for the cleanup.  Can you tell me a little about what the changes achieve?  Thanks!

**Comment by corneliusroemer** [comment]
This is just standard conda-forge build system updated. It's all automated, but I had to bump the build number so needed to make a PR from fork.

**Comment by corneliusroemer** [comment]
Close in favor of #307

**Pull request closed without merging**
