### PR TITLE
Feat: enable aarch64

### LINKED ISSUE #260: Please add aarch64 (linux) support
### Comment:

It would be great if you could also produce a conda package for linux-aarch64 - this is possible with conda-forge

### PR DESCRIPTION
**Pull request by corneliusroemer**
Resolves #260

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by corneliusroemer** [comment]
@BradHolmes This should work to add a linux-aarch64 build. You already create the binary, it's just not packaged here (yet).

**Comment by corneliusroemer** [comment]
@conda-forge-admin, please rerender

**Comment by corneliusroemer** [comment]
I squashed and rebased to make for a cleaner diff

**Comment by corneliusroemer** [comment]
Yay, now all builds pass as well, including the linux-arm64/aarch64! @BradHolmes

**Review by BradHolmes — APPROVED** [review]
Thank you for the nice addition.

**Comment by corneliusroemer** [comment]
Thank you! This was quite easy and helps me get ncbi-datasets-cli into an aarch64 docker container!

You need to merge it, otherwise it won't take effect, I don't (yet) have write access (until #265 is merged)

**Pull request merged**
